name: sundaymorningsattheriver
favicon: null
layout_spectrum: 0.0141743253916502
typography_spectrum: 0.9520014838781208
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.824100224301219
  lightness: 0.9840560879092664
  saturation: 0.858853075420484
  rhythmicContrast: 0.874923471128568
purpose: []
